services:
  frontend:
    build:
      context: . # Context should be set to the folder containing the Dockerfile
      dockerfile: src/Dockerfile
    ports:
      - "3000:80"  # Map port 80 in the container to port 3000 on the host
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Expose the backend on port 5000
    environment:
      - NODE_ENV=production
